### ISSUE TITLE
Better frontend

### ISSUE THREAD

**Issue by asgerius** [peleiden/rl-rubiks#1]
Page for GIFs, less bugginess, other goodies

**Comment by asgerius** [comment]
Bug where local host breaks site if not open

**Comment by sorenmulli** [comment]
Looks super nice! 
Observations from the `prod` website:
- Reset-button seems to not work.
- Agent names do not show up but solving works

**Comment by sorenmulli** [comment]
Would it be hard to allow the user to rotate the cube while the API is loading?

**Comment by asgerius** [comment]
No

**Comment by sorenmulli** [comment]
Nice to know

**Comment by asgerius** [comment]
Fixed
