### ISSUE TITLE
Last fixes before assignment

### ISSUE THREAD

**Issue by sorenmulli** [peleiden/rl-rubiks#27]
- [x] Naming of actions in frontend
- [x] Make sure log in train is nice (first impressions when running): Fix ModelConfig print and learning rate spacing
- [x] Clean up job script from accidental push (woops)
- [ ] Maybe prettify Readme with a gif of an impressive solve? :)

**Comment by oskarwiese** [comment]
Uhhh der mangler sku stadig 3, skynd jer!
